import { StyleSheet, Dimensions } from 'react-native';
import { themes } from '../../global/themes';

const { width } = Dimensions.get('window');
const cardWidth = (width - 48) / 2;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: themes.colors.beige,
    },
    headerCarrinho: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    botaoCarrinho: {
        position: 'relative',
        padding: 8,
    },
    badgeCarrinho: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: '#f44336',
        borderRadius: 10,
        minWidth: 18,
        height: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeTexto: {
        color: themes.colors.white,
        fontSize: 10,
        fontWeight: '700',
    },
    searchContainer: {
        paddingHorizontal: 16,
        marginBottom: 12,
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: themes.colors.white,
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 45,
        borderWidth: 1,
        borderColor: themes.colors.lightGray,
        gap: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: themes.colors.black,
        height: '100%',
    },
    categoriasContainer: {
        maxHeight: 50,
        marginBottom: 16,
    },
    categoriasContent: {
        paddingHorizontal: 16,
        gap: 8,
    },
    categoriaFilter: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: themes.colors.white,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: themes.colors.lightGray,
        gap: 4,
    },
    categoriaFilterAtivo: {
        backgroundColor: themes.colors.primary,
        borderColor: themes.colors.primary,
    },
    categoriaFilterIcon: {
        fontSize: 16,
    },
    categoriaFilterTexto: {
        fontSize: 14,
        color: themes.colors.darkGray,
    },
    categoriaFilterTextoAtivo: {
        color: themes.colors.white,
        fontWeight: '600',
    },
    lista: {
        padding: 16,
        paddingTop: 0,
    },
    listaVazia: {
        alignItems: 'center',
        padding: 40,
        width: '100%',
    },
    listaVaziaTexto: {
        color: themes.colors.darkGray,
        marginTop: 10,
        fontSize: 16,
        textAlign: 'center',
    },
    card: {
        width: cardWidth,
        backgroundColor: themes.colors.white,
        borderRadius: 16,
        padding: 12,
        margin: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    cardNome: {
        fontSize: 14,
        fontWeight: '600',
        color: themes.colors.black,
        flex: 1,
    },
    cardCategoria: {
        backgroundColor: themes.colors.lightBlue,
        borderRadius: 12,
        padding: 4,
    },
    categoriaIcon: {
        fontSize: 14,
    },
    cardDescricao: {
        fontSize: 12,
        color: themes.colors.darkGray,
        marginBottom: 12,
        height: 32,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    cardPreco: {
        fontSize: 16,
        fontWeight: '700',
        color: themes.colors.primary,
    },
    botaoComprar: {
        backgroundColor: themes.colors.primary,
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 6,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    botaoComprarTexto: {
        color: themes.colors.white,
        fontSize: 10,
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: themes.colors.beige,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        maxHeight: '80%',
    },
    modalCarrinhoContent: {
        maxHeight: '90%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitulo: {
        fontSize: 20,
        fontWeight: '700',
        color: themes.colors.black,
    },
    modalDescricao: {
        fontSize: 14,
        color: themes.colors.darkGray,
        marginBottom: 20,
        lineHeight: 20,
    },
    modalPrecoContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: themes.colors.lightGray,
    },
    modalPrecoLabel: {
        fontSize: 16,
        color: themes.colors.darkGray,
    },
    modalPreco: {
        fontSize: 24,
        fontWeight: '700',
        color: themes.colors.primary,
    },
    quantidadeContainer: {
        marginBottom: 20,
    },
    quantidadeLabel: {
        fontSize: 14,
        color: themes.colors.darkGray,
        marginBottom: 8,
    },
    quantidadeControls: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 20,
    },
    quantidadeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: themes.colors.lightBlue,
        justifyContent: 'center',
        alignItems: 'center',
    },
    quantidadeValor: {
        fontSize: 20,
        fontWeight: '600',
        color: themes.colors.black,
        minWidth: 40,
        textAlign: 'center',
    },
    modalTotal: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: themes.colors.lightGray,
    },
    modalTotalLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: themes.colors.black,
    },
    modalTotalValor: {
        fontSize: 20,
        fontWeight: '700',
        color: themes.colors.primary,
    },
    botaoAdicionar: {
        backgroundColor: themes.colors.primary,
        borderRadius: 12,
        height: 50,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    botaoAdicionarTexto: {
        color: themes.colors.white,
        fontSize: 16,
        fontWeight: '600',
    },
    carrinhoVazio: {
        alignItems: 'center',
        padding: 40,
    },
    carrinhoVazioTexto: {
        color: themes.colors.darkGray,
        marginTop: 10,
        fontSize: 16,
    },
    carrinhoLista: {
        maxHeight: 300,
    },
    carrinhoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: themes.colors.lightGray,
    },
    carrinhoItemInfo: {
        flex: 1,
    },
    carrinhoItemNome: {
        fontSize: 14,
        fontWeight: '600',
        color: themes.colors.black,
        marginBottom: 2,
    },
    carrinhoItemDetalhe: {
        fontSize: 12,
        color: themes.colors.gray,
        marginBottom: 2,
    },
    carrinhoItemTotal: {
        fontSize: 14,
        fontWeight: '600',
        color: themes.colors.primary,
    },
    carrinhoFooter: {
        marginTop: 20,
        paddingTop: 20,
        borderTopWidth: 2,
        borderTopColor: themes.colors.primary,
    },
    carrinhoTotal: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    carrinhoTotalLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: themes.colors.black,
    },
    carrinhoTotalValor: {
        fontSize: 20,
        fontWeight: '700',
        color: themes.colors.primary,
    },
    carrinhoAcoes: {
        flexDirection: 'row',
        gap: 12,
    },
    botaoLimpar: {
        flex: 1,
        backgroundColor: themes.colors.lightGray,
        borderRadius: 12,
        height: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    botaoLimparTexto: {
        color: themes.colors.darkGray,
        fontSize: 14,
        fontWeight: '600',
    },
    botaoFinalizar: {
        flex: 2,
        backgroundColor: themes.colors.primary,
        borderRadius: 12,
        height: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    botaoFinalizarTexto: {
        color: themes.colors.white,
        fontSize: 14,
        fontWeight: '600',
    },
});