import { StyleSheet } from 'react-native';
import { themes } from '../../global/themes';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: themes.colors.beige,
    },
    header: {
        padding: 16,
        paddingTop: 0,
    },
    botaoNovaMensagem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: themes.colors.primary,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    botaoNovaMensagemTexto: {
        color: themes.colors.white,
        fontSize: 16,
        fontWeight: '600',
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
    },
    subTitulo: {
        fontSize: 18,
        fontWeight: '600',
        color: themes.colors.black,
        marginBottom: 16,
    },
    lista: {
        paddingBottom: 16,
    },
    listaVazia: {
        alignItems: 'center',
        padding: 40,
    },
    listaVaziaTexto: {
        color: themes.colors.darkGray,
        marginTop: 10,
        fontSize: 16,
        textAlign: 'center',
    },
    botaoIniciar: {
        backgroundColor: themes.colors.primary,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        marginTop: 20,
    },
    botaoIniciarTexto: {
        color: themes.colors.white,
        fontSize: 14,
        fontWeight: '600',
    },
    card: {
        backgroundColor: themes.colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    cardNaoLido: {
        borderLeftWidth: 4,
        borderLeftColor: themes.colors.primary,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    cardTituloContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
    },
    cardNome: {
        fontSize: 16,
        fontWeight: '600',
        color: themes.colors.black,
    },
    naoLidoBadge: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: themes.colors.primary,
    },
    cardData: {
        fontSize: 12,
        color: themes.colors.gray,
    },
    cardAssunto: {
        fontSize: 14,
        fontWeight: '500',
        color: themes.colors.primary,
        marginBottom: 4,
    },
    cardMensagem: {
        fontSize: 14,
        color: themes.colors.darkGray,
        marginBottom: 8,
    },
    cardResposta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: themes.colors.lightBlue,
        padding: 8,
        borderRadius: 8,
    },
    cardRespostaTexto: {
        fontSize: 12,
        color: themes.colors.darkGray,
        flex: 1,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: themes.colors.beige,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        maxHeight: '90%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitulo: {
        fontSize: 20,
        fontWeight: '700',
        color: themes.colors.black,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputRow: {
        flexDirection: 'row',
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: '500',
        color: themes.colors.darkGray,
        marginBottom: 8,
        marginLeft: 4,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: themes.colors.white,
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 50,
        borderWidth: 1,
        borderColor: themes.colors.lightGray,
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: themes.colors.black,
        height: '100%',
    },
    textAreaContainer: {
        height: 'auto',
        minHeight: 120,
        paddingVertical: 12,
    },
    textArea: {
        height: 'auto',
        textAlignVertical: 'top',
    },
    botaoEnviar: {
        backgroundColor: themes.colors.primary,
        borderRadius: 12,
        height: 50,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginTop: 8,
        marginBottom: 24,
    },
    botaoEnviarTexto: {
        color: themes.colors.white,
        fontSize: 16,
        fontWeight: '600',
    },
    detalheContainer: {
        gap: 16,
    },
    detalheItem: {
        flexDirection: 'row',
        gap: 12,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: themes.colors.lightGray,
    },
    detalheResposta: {
        backgroundColor: themes.colors.lightBlue,
        padding: 12,
        borderRadius: 8,
        borderBottomWidth: 0,
    },
    detalheContent: {
        flex: 1,
    },
    detalheLabel: {
        fontSize: 12,
        color: themes.colors.gray,
        marginBottom: 2,
    },
    detalheValor: {
        fontSize: 14,
        color: themes.colors.black,
    },
    botaoExcluir: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: 16,
        marginTop: 20,
        marginBottom: 24,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#f44336',
    },
    botaoExcluirTexto: {
        color: '#f44336',
        fontSize: 16,
        fontWeight: '600',
    },
});